force-app/main/default/objects/To_Do__c/To_Do__c.object-meta.xml
<CustomObject>
    <description>These are the things to do!</description>
    <label>To Do</label>
    <nameField>
        <label>To Do Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Dos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do__c/fields/Actions__c.field-meta.xml
<CustomField>
    <fullName>Actions__c</fullName>
    <description>The actions of the To Do</description>
    <label>Actions</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action 1</fullName>
            </value>
            <value>
                <fullName>Action 2</fullName>
            </value>
            <value>
                <fullName>Action 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/To_Do__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>To Dos</relationshipLabel>
    <relationshipName>To_Dos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ToDoController.cls
/*
    ToDoController
        - Apex controller for LWC todo
        - TODO: Add this test class
        - Test class is ToDoControllerTest
*/
public with sharing class ToDoController {
    @AuraEnabled(cacheable=true)
    public static List<To_Do__c> getToDoList(Id userId) {
        return [
            SELECT Id, Name, Contact__c, Actions__c, Status__c,
                Contact__r.Name
            FROM To_Do__c
            WHERE CreatedById = :userId
            ORDER BY CreatedDate DESC
        ];
    }
}